config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :compras do
    get :confirmar, on: :member
  end

  root 'productos#index'
  get 'productos/autocomplete_producto_nombre'
  resources :productos

end

app/models/compra.rb
class Compra < ActiveRecord::Base
  has_many :items
  #accepts_nested_attributes_for :items, reject_if: :all_blank, allow_destroy: true

  def confirmar
    for item in items
      item.producto.update stock: item.producto.stock + item.cantidad
    end
  end

end

app/models/item.rb
class Item < ActiveRecord::Base

  attr_accessor :producto_nombre

  belongs_to :producto
  belongs_to :compra

  def producto_nombre=(un_nombre)
    self.producto = Producto.find_by nombre: un_nombre
  end

  def producto_nombre
    producto.nombre if producto
  end

end

app/models/producto.rb
class Producto < ActiveRecord::Base
  has_many :items

  accepts_nested_attributes_for :items

  before_save :default_stock
  #after_initialize :default_stock
  #after_create :default_stock

  validates :nombre, presence: true
  validates :precio, numericality: {greater_than_or_equal_to: 0.01}
  validates :stock, numericality: {greather_than_or_equal_to: 0}


  def to_s
    nombre
  end

  private

  def default_stock
    self.stock ||= 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/compras_controller.rb
class ComprasController < ApplicationController
  before_action :set_compra, only: [:show, :edit, :update, :destroy, :confirmar]

  # GET /compras
  # GET /compras.json
  def index
    @compras = Compra.all
  end

  # GET /compras/1
  # GET /compras/1.json
  def show
  end

  # GET /compras/new
  def new
    @compra = Compra.new
  end

  # GET /compras/1/edit
  def edit
    @item = Item.new
    # @item = @compra.items.build
  end

  # POST /compras
  # POST /compras.json
  def create
    @compra = Compra.new(compra_params)

    respond_to do |format|
      if @compra.save
        format.html { redirect_to @compra, notice: 'Compra was successfully created.' }
        format.json { render :show, status: :created, location: @compra }
      else
        format.html { render :new }
        format.json { render json: @compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /compras/1
  # PATCH/PUT /compras/1.json
  def update
    respond_to do |format|
      if @compra.update(compra_params)
        format.html { redirect_to @compra, notice: 'Compra was successfully updated.' }
        format.json { render :show, status: :ok, location: @compra }
      else
        format.html { render :edit }
        format.json { render json: @compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /compras/1
  # DELETE /compras/1.json
  def destroy
    @compra.destroy
    respond_to do |format|
      format.html { redirect_to compras_url, notice: 'Compra was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def confirmar
    @compra.confirmar
    redirect_to compras_path, notice: "La compra se confirmó!"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_compra
      @compra = Compra.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def compra_params
      params[:compra]
      #params.require(:compra).permit(items_attributes: [:id, :cantidad, :precio, :producto])
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to edit_compra_path(@item.compra), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      #params.require(:item).permit(:cantidad, :precio, :compra_id, :producto => [:nombre])
      # params.require(:item).permit(:cantidad, :precio, :compra_id, producto: [:nombre])
      params.require(:item).permit(:cantidad, :precio, :compra_id, :producto_nombre)
    end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]
  autocomplete :producto, :nombre, :full => true

  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.all

    if params[:nombre]
      @producto = Producto.nombre_like("%#{params[:nombre]}%").order('nombre')
    else
      @producto = Producto.new
    end
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    if producto_creado = Producto.find_by(nombre: @producto.nombre)
      producto_creado.precio = @producto.precio
      producto_creado.stock = producto_creado.stock + @producto.stock

      @producto = producto_creado
    end

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: 'Producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:nombre, :precio, :stock)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/compras_helper.rb
module ComprasHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/compras/_form.html.erb
<%= form_for(@compra) do |f| %>
  <% if @compra.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@compra.errors.count, "error") %> prohibited this compra from being saved:</h2>

      <ul>
      <% @compra.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/compras/edit.html.erb
<h1>Editing Compra</h1>

<ul>
  <% for item in @compra.items %>
    <li><%= item.cantidad %> - <%= item.producto %> (<%= item.precio %>)</li>
  <% end %>
</ul>

<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cantidad %><br>
    <%= f.number_field :cantidad, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :precio %><br>
    <%= f.text_field :precio %>
  </div>

  <div class="field">
    <%= f.label :producto %><br>
    <%#= f.collection_select :producto_id, Producto.all, :id, :nombre %>
    <%= f.text_field :producto_nombre, data: {autocomplete: productos_autocomplete_producto_nombre_path} %>
  </div>

  <%= f.hidden_field :compra_id, value: @compra.id %>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

<%= link_to 'Confirmar compra', confirmar_compra_path(@compra) %>

<%= link_to 'Show', @compra %> |
<%= link_to 'Back', compras_path %>

app/views/compras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Compras</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @compras.each do |compra| %>
      <tr>
        <td><%= link_to 'Show', compra %></td>
        <td><%= link_to 'Edit', edit_compra_path(compra) %></td>
        <td><%= link_to 'Destroy', compra, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Compra', new_compra_path %>

app/views/compras/new.html.erb
<h1>New Compra</h1>

<%= render 'form' %>

<%= link_to 'Back', compras_path %>

app/views/compras/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_compra_path(@compra) %> |
<%= link_to 'Back', compras_path %>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cantidad %><br>
    <%= f.number_field :cantidad %>
  </div>
  <div class="field">
    <%= f.label :precio %><br>
    <%= f.text_field :precio %>
  </div>

  <h3>Producto</h3>
  <!-- http://apidock.com/rails/ActionView/Helpers/FormHelper/fields_for -->

  <%= f.fields_for :producto do |producto_fields| %>
    <div class="field">
      <%= producto_fields.label :nombre %><br>
      <%= producto_fields.text_field :nombre %>
    </div>

    <div class="field">
      <%= producto_fields.label :total %><br>
      <%= producto_fields.label "$ 000000" %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Items</h1>

<table>
  <thead>
    <tr>
      <th>Cantidad</th>
      <th>Precio</th>
      <th>Producto</th>
      <th>Compra</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.cantidad %></td>
        <td><%= item.precio %></td>
        <td><%= item.producto %></td>
        <td><%= item.compra %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cantidad:</strong>
  <%= @item.cantidad %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @item.precio %>
</p>

<p>
  <strong>Producto:</strong>
  <%= @item.producto %>
</p>

<p>
  <strong>Compra:</strong>
  <%= @item.compra %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GiusComercio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/productos/_form.html.erb
<%= form_for(@producto) do |f| %>
  <% if @producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% @producto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre, data: {autocomplete: productos_autocomplete_producto_nombre_path} %>
  </div>
  <div class="field">
    <%= f.label :precio %><br>
    <%= f.text_field :precio %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/productos/edit.html.erb
<h1>Editing Producto</h1>

<%= render 'form' %>

<%= link_to 'Show', @producto %> |
<%= link_to 'Back', productos_path %>

app/views/productos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Productos</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Precio</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= producto.nombre %></td>
        <td><%= number_to_currency(producto.precio) %></td>
        <td><%= producto.stock %></td>
        <td><%= link_to 'Show', producto, { :class=>"btn btn-primary btn-sm" } %></td>
        <td><%= link_to 'Edit', edit_producto_path(producto), { :class=>"btn btn-warning btn-sm" } %></td>
        <td><%= button_to 'Destroy', producto, method: :delete, class: "btn btn-danger btn-sm", data: { confirm: 'Estás seguro?'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Producto', new_producto_path %>

app/views/productos/new.html.erb
<h1>New Producto</h1>

<%= render 'form' %>

<%= link_to 'Back', productos_path %>

app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @producto.nombre %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @producto.precio %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @producto.stock %>
</p>

<%= link_to 'Edit', edit_producto_path(@producto) %> |
<%= link_to 'Back', productos_path %>